export const sampleAudios = [
  {
    id: "hv_ha",
    label: "Joyful / Energetic",
    quadrant: "highValenceHighArousal",
    valence: 0.85,
    arousal: 0.85,
    fileName: "sample_hv_ha.mp3",
    src: "/audio/samples/sample_hv_ha.mp3",
    description: "High Valence / High Arousal sample",
  },
  {
    id: "hv_la",
    label: "Peaceful / Warm",
    quadrant: "highValenceLowArousal",
    valence: 0.85,
    arousal: 0.15,
    fileName: "sample_hv_la.mp3",
    src: "/audio/samples/sample_hv_la.mp3",
    description: "High Valence / Low Arousal sample",
  },
  {
    id: "lv_ha",
    label: "Tense / Intense",
    quadrant: "lowValenceHighArousal",
    valence: 0.15,
    arousal: 0.85,
    fileName: "sample_lv_ha.mp3",
    src: "/audio/samples/sample_lv_ha.mp3",
    description: "Low Valence / High Arousal sample",
  },
  {
    id: "lv_la",
    label: "Lonely / Quiet",
    quadrant: "lowValenceLowArousal",
    valence: 0.15,
    arousal: 0.15,
    fileName: "sample_lv_la.mp3",
    src: "/audio/samples/sample_lv_la.mp3",
    description: "Low Valence / Low Arousal sample",
  },
] as const;
